# Site settings
title: Random Thoughts
author: Javier Jiménez
email: ""
description: "Writing to think. Occasionally worth reading (?)"
baseurl: ""
url: "https://jajimer.github.io"
github_username: jajimer

theme: minima
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag